import type { Metadata } from "next";
import { Lalezar, Geist_Mono } from "next/font/google";

import "./globals.css";
import { DirectionProvider } from "@/components/ui/direction";


const lalezar = Lalezar({
  weight: "400",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${lalezar.className} ${geistMono.variable} antialiased bg-[#EAEFEF] dark:bg-[#25343F] relative`}
      >

        <DirectionProvider dir="rtl" direction="rtl" >
        {children}
        </DirectionProvider>
      </body>
    </html>
  );
}
